root: true

env:
  node: true
  es2020: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier

parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: module

plugins:
  - "@typescript-eslint"
  - import

rules:
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-non-null-assertion": off
  curly: [error, all]
  import/order:
    [
      2,
      {
        alphabetize: { caseInsensitive: true, order: asc },
        groups: [[external, builtin], internal, parent, sibling, index],
        newlines-between: never,
      },
    ]
  newline-before-return: error
  no-console: error
  no-shadow: error
